### ISSUE TITLE
Do not enable epel

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/ansible-role-redis#1]
This will not work on RHEL:
https://github.com/adfinis-sygroup/ansible-role-redis/blob/d2d06bcef09c4e935099b9ad1efca506460da524/tasks/installation.yml#L3

* `epel-release` is only available on CentOS.
* usually, epel can be enabled with a separate Ansible role (prerequisite)

Therefore, I suggest to remove this task.

**Comment by eyenx** [comment]
won't also work with Debian. Should be removed as I see it.
